apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mongo
  namespace: namespace-cnetdisk
spec:
  replicas: 1
  selector:
    matchLabels:
      podName: pod-mongo
  template:
    metadata:
      labels:
        podName: pod-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0.2
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data-volume
              mountPath: /data/db
      volumes:
        - name: mongo-data-volume
          persistentVolumeClaim:
            claimName: pvc-mongo
