apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
spec:
  nfs:
    server: 192.168.222.100
    path: /data/C-NetDisk/mongo/data
  storageClassName: storage-cnetdisk-mongo
  capacity:
    storage: 2G
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain